@localhost=localhost:4004/odata/v4/main-sercice

GET http://{{localhost}}/Customers
Content-Type: application/json

###

POST http://{{localhost}}/Customers
Content-Type: application/json

{
    "id": "c56ed007-3106-4a25-b053-32c2bc9060b2",
    "firstName": "Jose",
    "lastName": "Martins",
    "email": "jose.martins@b2rise.consulting"
}

###

DELETE http://{{localhost}}/Customers(id=)
Content-Type: application/json

{
    
}

###

PATCH http://{{localhost}}/Customers(id=c56ed007-3106-4a25-b053-32c2bc9060b2)
Content-Type: application/json

{
    "firstName": "Felipe"
}

###

GET http://{{localhost}}/Customers?$filter=endswith(firstName, '-22156291')

###
# Buscando dados com search
GET http://{{localhost}}/Customers?$search=firstName2

###
# Ordenando dados com orderby
GET http://{{localhost}}/Customers?$orderby=firstName desc,id desc