@localhost=localhost:4004/odata/v4/main-sercice
@id=e28b38e2-ef74-4c16-9eec-b11b340e362e
@customerId=22156291-ed69-4f98-bafe-d2f4c8d8a65e
@productId=adb90e43-df32-46e3-a965-afa6dd666307
@productId1=16631786-22ad-4e8e-ba58-f73036a79e27
@productId2=17323516-735a-4456-9c9b-4cda82376676

GET http://{{localhost}}/SaleOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://localhost:4004/odata/v4/main-sercice/SaleOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "20458062-931f-487f-9e22-2637b03d8686",
    "totalAmount": 4.98,
    "items": [
        {
            "id": "a3c2a3d8-976b-4f36-b22a-6c186e7440bd",
            "header_id": "{{id}}",
            "product_id": "{{productId1}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "9614a968-8a22-4066-a9c1-b9f438bf4bf0",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SaleOrderHeaders(id={{id}})
Content-Type: application/json

{
    
}

###

PUT http://{{localhost}}/SaleOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "teste"
}

###

GET http://{{localhost}}/SaleOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json

###

GET http://{{localhost}}/SaleOrderHeaders?$filter=totalAmount le 200000
Content-Type: application/json

###
# Expandindo os item
GET http://{{localhost}}/SaleOrderHeaders?$filter=totalAmount le 200000&$expand=items($expand=product),customer
Content-Type: application/json

###
GET http://{{localhost}}/SaleOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer


###
# Select
GET http://{{localhost}}/SaleOrderHeaders?$select=id,customer&$expand=customer($select=email)


###
# Descobrindo a quantidade de registro (Count)
GET http://{{localhost}}/SaleOrderHeaders/$count

###
# Paginando os registro
GET http://{{localhost}}/SaleOrderHeaders?$skip=0&$top=5

###
# Buscando dados com search
GET http://{{localhost}}/SaleOrderHeaders?$search=36ys&$filter=totalAmount gt 500